### ISSUE TITLE
Local Search

### ISSUE THREAD

**Issue by ScottWales** [coecms/clef#31]
Currently the search works by calling out to ESGF then matching search results against file checksums. Unfortunately the ESGF catalogue is not comprehensive - old versions of datasets get removed

**Add a way to search the local paths via MAS to retrieve datasets that have been removed from ESGF**

#### Challenges:

Version information is part of a dataset, not a file (one file can be a member of multiple dataset versions), so this must be retrieved from the DRS. The DRS for ua6 is unusable, but now that Synda is being used in al33 and oi10 that makes a local search possible.

The DRS entries are made up of both files and symlinks. It is not possible for the database to resolve symbolic links (this has to be done as part of the filesystem crawling) so for the moment we cannot link a DRS entry against the file metadata.

#### Implementation plan:

 * Add a new view `drs_path` as a generic DRS entry, with columns `path_id`, `project`. The project column will be used for [SQLalchemy joined table inheritance](http://docs.sqlalchemy.org/en/latest/orm/inheritance.html#joined-table-inheritance)
 * Add views for `drs_path_cmip5`, `drs_path_cmip6`, `drs_path_cordex` etc. as needed with each catalogue's components generated from the matching path
 * Add a python function that runs a search on these views given a set of constraints
 * Add a CLI option to search the local DRS entries instead of ESGF

**Comment by ScottWales** [comment]
CMIP5 DRS is described at https://cmip.llnl.gov/cmip5/docs/cmip5_data_reference_syntax.pdf

CMIP6 DRS is described at http://goo.gl/v1drZl

**Comment by paolap** [comment]
I started doing an alternative local_query to give something to work with with the "pipeline".
I've pushed this to the xrelease branch which is a copy of the current master plus these new functions.
I didn't use the DRS approach though I simply tried to use the attributes stored in the tables to search for the arguments passed by the user.
I'm quite sure there's a more efficient way to do this 

I'm doing this in three steps:
out=session.query(c5_metadata_dataset_link],C5Dataset).join(C5Dataset).filter_by(**kwargs) out1=out.join(Path).join(ExtendedMetadata).filter(ExtendedMetadata.variable == var)
The for each result in out1:
row=session.query(Path).join(c5_metadata_dataset_link).filter(Path.id == o.file_id).one_or_none()

This is the CMIP5 example, for CMIP6 I do the same but I don't need to filter for the variable.

I'm not even sure the first step is necessary but that's the only way I tried and would return all the DRS bits: ensemble, experiment, frequency etc. and the path
After this I call a function that return a list of dictionaries for every file, then I have a different function that return a list of dictionaries but this time with a dicitonary for each simualtion a 'filenames' key listing all the files and a 'periods' key listing all the ranges.
I'm working on changing the periods to two fields from_date to_date.

Then I want to add some checks on the arguments a user can pass so we can warn a user when it pass keys/values which don't exist.

At least these last bits should be useful even if we change the main search.

**Comment by ScottWales** [comment]
Simplified version could look like
```
import clef.db
import clef.model as cm
import os

clef.db.connect()
s = clef.db.Session()

r = (s.query(cm.Path.path.label('path'), 
            *[c.label(c.name) for c in cm.C5Dataset.__table__.columns if c.name != 'dataset_id'],
            *[c.label(c.name) for c in cm.ExtendedMetadata.__table__.columns if c.name != 'file_id']
           )
     .join(cm.Path.extended)
     .join(cm.Path.c5dataset)
     .filter_by(model='ACCESS1.0')
     .limit(5))

df = pandas.read_sql(r.selectable, con=s.connection())
df['dir'] = df['path'].map(os.path.dirname)
df
```

**Comment by paolap** [comment]
The simplified version is now part of the current release.
I had to put a separate filter for the "variable" filed in CMIP5.
Could be written better but currently works and is returning results as dictionaries as requested, although I kept pandas to run the query and do the first manipulations of the results that was a lot more efficient approach

**Comment by paolap** [comment]
This is now in the latest release
