### ISSUE TITLE
CMIP6 ESGF search doesn't include variable

### ISSUE THREAD

**Issue by paolap** [coecms/clef#32]
Just discovered this:

WHERE extended_metadata.variable ILIKE ANY (%(param_1)s)
INFO:sqlalchemy.engine.base.Engine:{'param_1': ['tntmp']}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): esgf-node.llnl.gov
DEBUG:urllib3.connectionpool:https://esgf-node.llnl.gov:443 "GET /esg-search/search?fields=checksum%2Cid%2Cdataset_id%2Ctitle%2Cversion&offset=0&limit=1000&distrib=True&replica=False&type=File&format=application%2Fsolr%2Bjson&activity_id=CMIP&experiment_id=amip&table_id=CFmon&project=CMIP6 HTTP/1.1" 200 3971

while I passed the tntmp value for variable is not included in the ESGF search so I get all the missing variables dataset-ids as a result.

Simply eliminating the "terms" selection based on local values and putting terms['variable_id'] = variable_id  fixes the issue. Since we have validations we should eliminate this step which risks to exclude anything whhc is not yet available locally, very likely for CMIP6.

**Comment by ScottWales** [comment]
Done in add-request branch

**Comment by paolap** [comment]
This should be part of the release now
