### ISSUE TITLE
datasets appearing both in local and as missing

### ISSUE THREAD

**Issue by paolap** [coecms/clef#33]
Just found out this:

~/.local/bin/clef cmip5 --variable tas --experiment historical --table day --ensemble r2i1p1 --model MIROC5
/g/data1b/al33/replicas/CMIP5/combined/MIROC/MIROC5/historical/day/atmos/day/r2i1p1/v20120710/tas/
('cmip5.output1.MIROC.MIROC5.historical.day.atmos.day.r2i1p1.v20120710',)
The following datasets are not yet available in the database, but they have been requested or recently downloaded
cmip5.output1.MIROC.MIROC5.historical.day.atmos.day.r2i1p1.v20120710. status: 'done'

The MIROC5 data has already been downloaded and is also in the database, still is considered missing from the tool. I reckon this happens because the directory with "combined" doesn't match the dataset_id "output1"

I've printed out the dataset_id for the missing files, it then gets recognised by searching the queue status online. It shouldn't even go there since that's check only dataset_ids which are "missing"

I imagine this would happen if somewhere we build the dataset_id from the path, but I can't find anywhere this is happening in the code

**Comment by ScottWales** [comment]
The MIROC files aren't being found because they have not all been scanned into MAS

**Comment by paolap** [comment]
I'm still getting examples of this which can be confusing, maybe we should consider printing something when this happens.
Example:
[pxp581@vdi-n1 clef]$ ~/.local/bin/clef cmip5 -m MRI-AGCM3.2H -t Amon -v va -e amip
/g/data1b/al33/replicas/CMIP5/combined/MRI/MRI-AGCM3-2H/amip/mon/atmos/Amon/r1i1p1/v20120701/va/

Available on ESGF but not locally:
cmip5.output1.MRI.MRI-AGCM3-2H.amip.mon.atmos.Amon.r1i1p1.v20120701 va
[pxp581@vdi-n1 clef]$ ~/.local/bin/clef --local cmip5 -m MRI-AGCM3.2H -t Amon -v va -e amip

This is in fact even more complex because the local search doesn't return anything for models which appears both in esgf local and ass missing. need to investigate this better

**Comment by paolap** [comment]
the local search issue wasn't related and it is now solved
