### ISSUE TITLE
keeping free text query?

### ISSUE THREAD

**Issue by paolap** [coecms/clef#34]
I'm running some tests on free text query and I'm getting many mre results each time that by specifying the exact constraints for the values, I'm wondering if is it worth keeping this functionality or if it's just likely to confuse the users or produce many more results that if they're obliged to define the arguments. Another issue is that we can't validate what they passed against the vocabularies.

**Comment by ScottWales** [comment]
Document this as an advanced option
Cannot do request with fts

**Comment by paolap** [comment]
We can close this as we are not going to introduce back free text query, at least not for the moment
