### ISSUE TITLE
rr3/publications results are not filtered based on project

### ISSUE THREAD

**Issue by paolap** [coecms/clef#35]
As an example:
clef --request cmip5   -e 1pctCO2  -t Amon -v tas
has among the many results:

/g/data1/rr3/publications/CMIP5/output1/UNSW/CSIRO-Mk3L-1-2/1pctCO2/mon/atmos/Amon/r3i1p1/v20170728/tas/
/g/data1/rr3/publications/PMIP3/output/UNSW/CSIRO-Mk3L-1-2/1pctCO2/mon/atmos/Amon/r1i1p1/v20170728/tas/

somewhere we must be assuming that anything in rr3 is CMIP5 while only

/g/data/rr3/publications/CMIP5 should be here!

**Comment by ScottWales** [comment]
Which branch is this for? Looks like `--request` in the master branch is a no-op

**Comment by paolap** [comment]
that would be add-request, but the issue should also show using local in the beta release

**Comment by ScottWales** [comment]
* [ ] Add sample non-cmip5 data to the test dataset db/sample_rr3_paths.txt
* [ ] Add test that 'cmip5' search should not return these paths
