### ISSUE TITLE
Enhancement: the % wilcard doesn't work anymore

### ISSUE THREAD

**Issue by paolap** [coecms/clef#36]
This is because we're using click choice to validate the arguments passed by the user. I suppose we could have our own class of clickChoice that treats a string with % in the same way.
Another feedback we received was it would be nice to be able to pass a list of arguments, so
--variable tasmin tasmax
rather then 
--variable tasmin --variable tasmax

again i think we can fix this by creating our own class, none of this is terribly urgent.

**Comment by ScottWales** [comment]
Change documentation to remove mention of this feature

**Comment by paolap** [comment]
this can be closed as we're not implementing this feature
