### ISSUE TITLE
Issue in ESGF response for latest==False

### ISSUE THREAD

**Issue by paolap** [coecms/clef#41]
Running this search in ESGF:

https://esgf-data.dkrz.de/esg-search/search?fields=checksum%2Cid%2Cdataset_id%2Ctitle%2Cversion&offset=0&limit=1000&distrib=True&replica=False&latest=False&type=File&format=application%2Fsolr%2Bjson&project=CMIP5&experiment=historical&model=ACCESS1.0&cmor_table=Amon&variable=tasmin

corresponding to

clef cmip5 --variable tasmin --experiment historical --table Amon -m ACCESS1.0 --all-versions

produce results as if the variable is not specified, running with latest=True is fine

If you look at the json response for both, with latest True you get only variable=['tasmin']
with latest=False: "variable":["cl",
          "cli",
          "clivi",
          "clt",
          "clw",... all the variables in the same dataset

I will try to filter this using the 'id' filed which should contain .<variable>_ in it as for example:
"id":"cmip5.output1.CSIRO-BOM.ACCESS1-0.historical.mon.atmos.Amon.r1i1p1.v20120727.tasmin_Amon_ACCESS1-0_historical_r1i1p1_185001-200512.nc_0|esgf.nci.org.au",

**Comment by paolap** [comment]
The patch works, but i'm using it with any search, maybe we could rewrite it so it runs only with CMIP5 / latest=False which is when it happens. I've double checked CMIP6 and there doesn't occur, i think also because the datasets there don't have more then one variable.
I've pushed this to master

**Comment by ScottWales** [comment]
NCI borked their published data for old versions of ACCESS, each file reports having every variable. The most recent file version is fixed
