### ISSUE TITLE
for 3.1 release installation in clef-test: exception handling not working

### ISSUE THREAD

**Issue by paolap** [coecms/clef#42]
When I run 
> clef cmip5  
I get a full error instead of the exception handling telling me to constrain more my search

**Comment by paolap** [comment]
Just git some feedback on this by one user, we should really only print a statement that includes only the last bit of the exception.
He also added that he thought he got that by putting in a request that was fairly defined already
probably CMIP5: sic, day, historical all models
The number of datasets wouldn't be really high but because you have some modelling group that have created a file for each year you can easily passed the maximum number allowed.
Either we raise this or we tailor it depending on the attributes.
Options: 
- frequency of  results, i.e. allowing more results for daily/hourly frequency
- number of attributes passed so distinguish between when you do not pass enough specifications
  i.e. set a higher limit if you have defined your request sufficiently as in this case he used 3 constraints then if you pass only two or one constraint
- a combination of number and which attributes??

**Comment by ScottWales** [comment]
Both issues appear resolved & don't produce stack traces.

The limit on number of items returned is because we want to be considerate to the ESGF nodes we're querying, and not hammer them with huge queries. The NCI node now has improved handling of distributed queries though, so that might be less of an issue
