### ISSUE TITLE
member_id in C6Dataset is wrong

### ISSUE THREAD

**Issue by paolap** [coecms/clef#46]
Working on the local search I discovered that member_id in the CMIP6 table is wrong.
We build this value by joinin

sub_experiment_id + '-' + variant_label

In most cases sub_exp. is none and member_id=label_id.
I found this example for IPSL-CM6A-LR model where sub-experiment-id returned 'none' as a string and the member_id is "none-r1i1p1f1"

**Comment by ScottWales** [comment]
This should now be fixed, sub_experiment_id is only added if not 'none'
