### ISSUE TITLE
Web search URL is incorrect

### ISSUE THREAD

**Issue by ScottWales** [coecms/clef#48]
The reported web search URL when no matches are found on ESGF is incorrect

```
$ clef cmip5 --model BCC-CSM1.1 --variable tas --experiment historical --table day
...
clef.esgf.ESGFException: No matches found on ESGF, check at https://esgf-data.dkrz.de/esg-search/search/cmip5?query=&distrib=True&replica=False&latest=True&project=CMIP5&experiment=historical&model=BCC-CSM1.1&cmor_table=day&variable=tas
```

This URL should be https://esgf-data.dkrz.de/search/cmip5-dkrz?query=&distrib=True&replica=False&latest=True&project=CMIP5&experiment=historical&model=BCC-CSM1.1&cmor_table=day&variable=tas

**Comment by paolap** [comment]
is this in release? I think I've done it and noticed before, so it must be fixed somewhere else :-)

**Comment by paolap** [comment]
actually that was my misunderstanding I thought we were printing exactly the same url. In any case I'll fix that in xrelease, where I've also got rid of the exception that looks way too much like an error

**Comment by paolap** [comment]
solved in the latest release
