### ISSUE TITLE
Error in mk3 results

### ISSUE THREAD

**Issue by ScottWales** [coecms/clef#83]
The directory returned by this search does not exist

```
$ clef --local cmip5 -m CSIRO-Mk3-6-0 -e historical -t Omon --ensemble r1i1p1 -v tos --latest
/g/data1/rr3/publications/CMIP5/output1/CSIRO-QCCCE/CSIRO-Mk3-6-0/historical/mon/ocean/Omon/r1i1p1/latest/tos
```

**Comment by ScottWales** [comment]
tos is not in the latest directory, only in `v20120213`. There are also more variables only in `v20110518`

**Comment by paolap** [comment]
Hi Scott,

I'm not sure what's going here, we knew about this issue already, in fact I forgot but meant to say to NCI that they aren't linking all the latest versions correctly.
At the time we decided to pass whatever we found unchanged 
From code.py in master:

def fix_path(path):
    '''Get path from query results and replace al33 output1/2 dirs to combined 
        and rr3 ACCESS "/files/" path to "/latest/"
    '''
    if '/al33/replicas/CMIP5/output' in path:
        return re.sub(r'replicas\/CMIP5\/output[12]?\/','replicas/CMIP5/combined/',path)
    elif '/al33/replicas/CMIP5/unsolicited' in path:
        return path.replace('unsolicited','combined')
    elif '/rr3/publications/CMIP5/output1/CSIRO-BOM' in path:
        dirs=path.split("/")
        var = dirs[-2].split("_")[0]
        return "/".join(dirs[0:-3]+['latest',var,dirs[-1]])
    else:
        return path

We're not doing anything with the CSIRO-QCCCE data it should just return the path as it is.
It is also covered in the tests, although I realised now that I made a mistake in there, double p in pubblications:

def test_fix_path():
    ...
    dir2 = '/g/data/rr3/pubblications/CMIP5/output1/CSIRO-QCCCE/more/files/tas_20110518/'
    ...
   
    assert fix_path(dir2) == '/g/data/rr3/pubblications/CMIP5/output1/CSIRO-QCCCE/more/files/tas_20110518/'
....
So this test would pass regardless I wonder what the DB is returning.
I'll make more checks tomorrow

**Comment by paolap** [comment]
Somehow something I did recently in my env on the VDI fixes this, it doesn't happen for me as along as I don't exclude my local env
Still apart from fixing the test I didn't do anything different, or at least not directly in regard to this.

**Comment by paolap** [comment]
This should be solved by changing the filters in esgf.py branch localfix
